name: prime_web
description: A new Flutter project.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_dynamic_links: ^5.4.8
  firebase_in_app_messaging: ^0.7.4+8
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^16.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_mobile_ads: ^4.0.0
  in_app_review: ^2.0.8
  lottie: ^3.0.0
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  provider: ^6.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  change_app_package_name: ^1.1.0


dependency_overrides:
  lottie: ^2.7.0
  permission_handler: ^11.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: SegUI
      fonts:
        - asset: assets/fonts/segoeui.ttf
        - asset: assets/fonts/seguisb.ttf
          weight: 900